# -*- coding: utf-8 -*-
"""16-NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1772yhLUmZz4jfag6_TdiYhBg9-sgymzO

# <font color='blue'>Python Fundamentos - NumPy</font>
"""

# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

"""## NumPy
<details>
    <summary>
        <a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Clique para mais detalhes</a>
    </summary>
    <br>
   
NumPy é um pacote para computação científica em Python. <br>
É uma biblioteca Python que fornece um objeto do tipo array. <br>
Um array pode ter uma ou várias dimensões (vetores ou matrizes). <br>
No núcleo do pacote NumPy, está o objeto ndarray. <br>
Existem algumas diferenças importantes entre as matrizes NumPy e as sequências Python padrão: <br>

- O array NumPy é criado com um tamanho fixo, ao contrário das listas Python, que podem crescer dinamicamente. Alterar o tamanho de um ndarray criará um novo array e excluirá o original. <br>
- Os elementos em um array NumPy devem ser todos do mesmo tipo de dado e, portanto, terão o mesmo tamanho na memória. Um objeto do tipo lista pode ter elementos de qualquer tipo de dado. <br>
- Os arrays NumPy facilitam operações matemáticas avançadas e outros tipos de operações em um grande número de dados. Normalmente, essas operações são executadas de forma mais eficiente, mais rápida e com menos código do que quando utilizando objetos do tipo lista.

</details>
"""

# Importando o pacote NumPy
import numpy as np

"""### Criando Arrays
É possível criar um array a partir de uma lista ou uma tupla usando o método array.
"""

# Criando um array com uma dimensão (com um axis) a partir de uma lista
vetor1 = np.array([2, 3, 4, 5, 6, 7, 8, 9])
vetor1

# Criando um array com uma dimensão (com um axis) a partir de uma tupla
vetor2 = np.array((10, 11, 12, 13, 14, 15, 16, 17, 18))
vetor2

# Criando um array com duas dimensões (com dois axes) sendo 2 linhas e 3 colunas utilizando uma lista de listas
# Cada lista é uma linha da matriz e a quantidade de elementos de uma lista, define o número de colunas
# O primeiro axis (linhas) tem tamanho 2
# O segundo axis (colunas) tem tamanho 3
matriz1 = np.array([[10, 20, 30], [40, 50, 60]])
matriz1

# Criando um array com duas dimensões (com dois axes) sendo 3 linhas e 2 colunas utilizando uma lista de tuplas
# Cada tupla é uma linha e a quantidade de elementos das tuplas é o número de colunas.
# O primeiro axis (linhas) tem tamanho 3
# O segundo axis (colunas) tem tamanho 2
matriz2 = np.array([(15, 25), (35, 45), (55, 65)])
matriz2

# Verificando o tipo de dado
type(matriz2)

"""### Slicing
Os arrays com uma dimensão podem ser indexados e fatiados de maneira muito semelhante às listas e outras sequências Python. <br>
Arrays multidimensionais possuem um índice por dimensão
"""

# Imprimindo o array
vetor1

# Recuperando o primeiro elemento do array
vetor1[0]

# Recuperando os elementos da posição 0 até a posição 3
vetor1[0:3]

# Imprimindo o array
matriz1

# Recuperando o elemento que está na primeira linha e na primeira coluna
matriz1[0, 0]

# Recuperando o elemento que está na segunda linha e na terceira coluna
matriz1[1, 2]

# Alterando o elemento que está na primeira linha e segunda coluna
matriz1[0, 1] = 88
matriz1

# Imprimindo o array
matriz2

# Recuperando as linhas 0, 1 e 2 da primeira coluna
matriz2[0:3, 0]

# Imprimindo o array
matriz1

# Recuperando todas as linhas da segunda e terceira coluna.
# O número ao lado direito do sinal de dois pontos é exclusivo
matriz1[:, 1:3]

"""### Métodos e atributos de um array"""

# Verificando a quantidade de dimensões de um array
vetor2.ndim

# Verificando a quantidade de dimensões de um array
matriz1.ndim

# Imprimindo um array
vetor2

# Verificando o formato de um array
vetor2.shape

# Imprimindo um array
matriz1

# Verificando o formato de um array
matriz1.shape

# Imprimindo um array
matriz2

# Verificando o formato de um array
matriz2.shape

# Verificando o tipo de dado dos elementos de um array
matriz2.dtype

# Retorna a quantidade de elementos de um array
matriz2.size

# Retorna a soma dos elementos de um array
matriz2.sum()

# Imprimindo um array
matriz1

# Retorna a soma de cada COLUNA
matriz1.sum(axis=0)

# Retorna a soma de cada LINHA
matriz1.sum(axis=1)

# Imprimindo um array
vetor2

# Retorna a soma acumulada dos elementos de um array
vetor2.cumsum()

# Retorna a média dos elementos de um array
vetor2.mean()

# Retorna a mediana dos elementos de um array
np.median(vetor2)

# Retorna a variância dos elementos de um array.
# A variância indica a distância que os valores se encontram em relação à média.
vetor2.var()

# Retorna o desvio padrão dos elementos de um array.
# O desvio padrão é a raiz quadrada da variância
vetor2.std()

# Retornando o valor máximo e mínimo dos elementos de um array
print("O maior valor é", vetor2.max(), "e o menor valor é", vetor2.min())

# Criando um array com valores sequenciais. Parecido com a função buil-in range
# [start: end: step]
vetor3 = np.arange(2, 20, 2)
vetor3

# Criando um array com valores sequenciais.
vetor4 = np.arange(10)
vetor4

# Criando um array de duas dimensões com valores sequenciais.
matriz3 = np.arange(12).reshape(3, 4)
matriz3

# Mudando formato do array
matriz3.reshape(6, 2)

# Mudando formato do array informando apenas a quantidade de linhas
matriz3.reshape(2, -1)

# Mudando formato do array informando apenas a quantidade de colunas
matriz3.reshape(-1, 3)

# Converte uma matriz em um vetor
matriz3.flatten()

# Criando um vetor com números aleatórios
# [start: end: size]
vetor5 = np.random.randint(5, 100, size=8)
vetor5

# Criando um array de duas dimensões com valores aleatórios.
matriz4 = np.random.randint(1, 1000, size=15).reshape(5, 3)
matriz4

# Criando um vetor especificando a quantidade de elementos dentro de um intervalo.
# O último elemento é inclusivo.
vetor6 = np.linspace(1, 100, 20)
vetor6

# Criando uma matriz de zeros
matrizZeros = np.zeros((4, 6))
matrizZeros

# Criando uma matriz com todos os elementos iguais a 1
matrizUm = np.ones([4, 4])
matrizUm

# Contar valores únicos no array NumPy
np.unique(matrizZeros, return_counts=True)

# Imprimindo uma variável
matriz2

# Inserindo uma nova linha na matriz
matriz2 = np.append(matriz2, [[1,2]], axis=0)
matriz2

# Inserindo uma nova coluna na matriz
matriz2 = np.append(matriz2, [[1],[2],[3], [4]], axis=1)
matriz2

"""### Operações básicas"""

# Criando dois arrays com uma dimensão
v1 = np.array([20, 30, 40, 50])
v2 = np.arange(4)
print(v1)
print(v2)

# Somando os arrays
v1 + v2

# Subtraindo os arrays
v1 - v2

# Comparando arrays
v1 == v2

# Elevando cada elemento a uma determinada potência
v2**2

# Multiplicando elementos de dois arrays
v1 * v2

# Criando matrizes
m1 = np.array([[5, 2],
               [0, 1]])
m2 = np.array([[2, 0],
               [3, 4]])

# Multiplicação de matrizes
m1.dot(m2)

"""### Exercícios

1 - Faça uma função chamada gera matriz que recebe como parâmetros de entrada (a, b, c, m) e que
tem como retorno um array Numpy de formato m × m (matriz quadrada), onde os elementos são os c
números igualmente espaçados obtidos ao se dividir o intervalo [a, b]. Caso não seja
possível construir tal array, a função deve retornar a mensagem "Não é possível
construir a matriz".
"""

# Importando o pacote NumPy
import numpy as np

# Definindo a função
def geraMatriz1(a, b, c, m):
    if (m * m == c):
        return np.random.randint(a, b, size=c).reshape(m, m)
    else:
        print("Não é possível construir a matriz")

# Chamando a função
geraMatriz1(0, 10, 16, 4)

# Chamando a função
geraMatriz1(0, 10, 20, 4)

"""### Tratamento de Exceções
Uma exceção ocorre quando o código está sendo executado.<br>
O código está sintaticamente correto, mas apresenta erro durante a execução.
"""

# Não é possível criar uma matriz com uma quantidade de elementos que não cabe no seu formato
np.random.randint(0, 10, size=20).reshape(4, 4)

# Definindo a função
def geraMatriz2(a, b, c, m):
    try:
        return np.random.randint(a, b, size=c).reshape(m, m)
    except ValueError as mensagemValueError: # Erro de valor
        print(mensagemValueError)
    except IOError as mensagemIOError: # Erro de entrada e saída
        print(mensagemIOError)
    except ZeroDivisionError as mensagemZeroDivisionError: # divisão por zero
        print(mensagemZeroDivisionError)
    except NameError as mensagemNameError: # variável não foi definida:
        print(mensagemNameError)
    else:
        print("Não é possível criar a matriz")

# Chamando a função
geraMatriz2(1, 100, 10, 4)

"""2 - Modifique a função do exercício anterior para imprimir:<br>
- a matriz criada; <br>
- a média e o desvio padrão das linhas; <br>
- a média e desvio padrão das colunas.
"""

# Definindo a função
def geraMatriz3(a, b, c, m):
    np.random.seed(5)
    try:
        matriz = np.random.randint(a, b, size=c).reshape(m, m)
        print(matriz)
        print("Média das linhas:", matriz.mean(axis=1))
        print("Desvio padrão das linhas:", matriz.std(axis=1))
        print("Média das colunas:", matriz.mean(axis=0))
        print("Desvio padrão das colunas:", matriz.std(axis=0))
    except ValueError as mensagemValueError:
        print(mensagemValueError)

# Chamando a função
geraMatriz3(1, 100, 16, 4)

"""3 - Modifique a função do exercício anterior para retornar uma matriz com a média e o desvio padrão das linhas e colunas."""

# Definindo a função
def geraMatriz4(a, b, c, m):
    np.random.seed(5)
    try:
        matriz = np.random.randint(a, b, size=c).reshape(m, m)
        print(matriz)
        print("Média das linhas:", matriz.mean(axis=1))
        print("Desvio padrão das linhas:", matriz.std(axis=1))
        print("Média das colunas:", matriz.mean(axis=0))
        print("Desvio padrão das colunas:", matriz.std(axis=0))

        return np.array([(matriz.mean(axis=1)), (matriz.std(axis=1)), (matriz.mean(axis=0)), (matriz.std(axis=0))])
    except ValueError as mensagemValueError:
        print(mensagemValueError)

# Chamando a função
geraMatriz4(1, 100, 25, 5)

"""4 - Utilize a função do exercício anterior para gerar uma matriz. A partir dessa matriz gerada, utilize o conceito de fatiamento para criar uma nova matriz com os valores das duas últimas colunas."""

# Chamando a função
m = geraMatriz4(1, 100, 25, 5)
m

# Criando uma nova matriz utilizando fatiamento
m2 = m[:, 3:5]
m2

